version: "3.8"

services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # WebUI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ../data/raw:/mnt/data
      - ../data/json:/mnt/json
      - ../data/certs:/etc/minio/certs
    command: minio server /mnt/data --console-address ":9001"
