apiVersion: 1

datasources:
  - name: PostgreSQL - Telco Warehouse
    type: grafana-postgresql-datasource
    uid: telco-postgres-ds
    access: proxy
    url: postgres_dw:5432
    database: telco_warehouse
    user: telco_admin
    secureJsonData:
      password: telco_pass
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: true
